name: cal-val-prototype
channels:
  - conda-forge
  - defaults
dependencies:
  - python =3.11
  - numpy >=1.26.4
  - pandas >=2.2.2
  - shapely >=2.0.5
  - geopandas >=1.0.1
  - lxml >=5.2.2
  - beautifulsoup4 >=4.12.3
  - gdal ==3.9.1
  - rasterio ==1.3.10
  - xarray >=2024.10.0
  - scipy >=1.14.1
  - netcdf4 >=1.7.2